version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: telugu-story-engine:latest
    container_name: telugu-story-engine
    restart: unless-stopped
    ports:
      - "12000:12000"  # API server
      - "12001:12001"  # Dashboard
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - ENVIRONMENT=production
      - USE_GPU=true
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - AI4BHARAT_API_KEY=${AI4BHARAT_API_KEY:-}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/story_engine
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=${API_KEY:-telugu-story-engine-api-key}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - DASHBOARD_SECRET_KEY=${DASHBOARD_SECRET_KEY:-telugu-story-engine-dashboard-secret}
    depends_on:
      - db
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: all

  db:
    image: postgres:15-alpine
    container_name: telugu-story-engine-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=story_engine
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: telugu-story-engine-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: telugu-story-engine-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@telugu-ai.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    container_name: telugu-story-engine-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    container_name: telugu-story-engine-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: